var annotated_dup =
[
    [ "magic_enum", "d2/da7/namespacemagic__enum.html", [
      [ "customize", "d4/d94/namespacemagic__enum_1_1customize.html", [
        [ "enum_range", "d8/dae/structmagic__enum_1_1customize_1_1enum__range.html", null ]
      ] ],
      [ "detail", "dd/d3d/namespacemagic__enum_1_1detail.html", [
        [ "case_insensitive", "dc/d83/classmagic__enum_1_1detail_1_1case__insensitive.html", "dc/d83/classmagic__enum_1_1detail_1_1case__insensitive" ],
        [ "constexpr_hash_t", "df/d3b/structmagic__enum_1_1detail_1_1constexpr__hash__t.html", null ],
        [ "constexpr_hash_t< Value, std::enable_if_t< is_enum_v< Value > > >", "dd/d86/structmagic__enum_1_1detail_1_1constexpr__hash__t_3_01_value_00_01std_1_1enable__if__t_3_01is__e9e2c5e2956f56ac40bc9b9bfd6fddd64.html", "dd/d86/structmagic__enum_1_1detail_1_1constexpr__hash__t_3_01_value_00_01std_1_1enable__if__t_3_01is__e9e2c5e2956f56ac40bc9b9bfd6fddd64" ],
        [ "constexpr_hash_t< Value, std::enable_if_t< std::is_same_v< Value, string_view > > >", "da/d04/structmagic__enum_1_1detail_1_1constexpr__hash__t_3_01_value_00_01std_1_1enable__if__t_3_01std_137d7a367bcc828d5278b8d9f2bcfdbfa.html", "da/d04/structmagic__enum_1_1detail_1_1constexpr__hash__t_3_01_value_00_01std_1_1enable__if__t_3_01std_137d7a367bcc828d5278b8d9f2bcfdbfa" ],
        [ "enable_if_enum", "dd/da3/structmagic__enum_1_1detail_1_1enable__if__enum.html", null ],
        [ "enable_if_enum< true, T, R >", "d3/de4/structmagic__enum_1_1detail_1_1enable__if__enum_3_01true_00_01_t_00_01_r_01_4.html", "d3/de4/structmagic__enum_1_1detail_1_1enable__if__enum_3_01true_00_01_t_00_01_r_01_4" ],
        [ "has_is_flags", "d6/d6c/structmagic__enum_1_1detail_1_1has__is__flags.html", null ],
        [ "has_is_flags< T, std::void_t< decltype(customize::enum_range< T >::is_flags)> >", "d9/d2b/structmagic__enum_1_1detail_1_1has__is__flags_3_01_t_00_01std_1_1void__t_3_01decltype_07customiz5850fc280780eb0d4e359edf8de2e402.html", null ],
        [ "is_scoped_enum", "d8/d3a/structmagic__enum_1_1detail_1_1is__scoped__enum.html", null ],
        [ "is_scoped_enum< T, true >", "d7/d0e/structmagic__enum_1_1detail_1_1is__scoped__enum_3_01_t_00_01true_01_4.html", null ],
        [ "is_unscoped_enum", "db/d31/structmagic__enum_1_1detail_1_1is__unscoped__enum.html", null ],
        [ "is_unscoped_enum< T, true >", "d2/dad/structmagic__enum_1_1detail_1_1is__unscoped__enum_3_01_t_00_01true_01_4.html", null ],
        [ "range_max", "d5/d1b/structmagic__enum_1_1detail_1_1range__max.html", null ],
        [ "range_max< T, std::void_t< decltype(customize::enum_range< T >::max)> >", "db/dbf/structmagic__enum_1_1detail_1_1range__max_3_01_t_00_01std_1_1void__t_3_01decltype_07customize_1_35692f6e889269924f0d80e52c12ef1d.html", null ],
        [ "range_min", "df/def/structmagic__enum_1_1detail_1_1range__min.html", null ],
        [ "range_min< T, std::void_t< decltype(customize::enum_range< T >::min)> >", "d9/dad/structmagic__enum_1_1detail_1_1range__min_3_01_t_00_01std_1_1void__t_3_01decltype_07customize_1_b5db5546fae27b586c6e1893b42c0f44.html", null ],
        [ "static_string", "dc/dc9/classmagic__enum_1_1detail_1_1static__string.html", "dc/dc9/classmagic__enum_1_1detail_1_1static__string" ],
        [ "static_string< 0 >", "d7/dfa/classmagic__enum_1_1detail_1_1static__string_3_010_01_4.html", "d7/dfa/classmagic__enum_1_1detail_1_1static__string_3_010_01_4" ],
        [ "supported", "de/db2/structmagic__enum_1_1detail_1_1supported.html", null ],
        [ "underlying_type", "d0/d95/structmagic__enum_1_1detail_1_1underlying__type.html", null ],
        [ "underlying_type< T, true >", "d2/db7/structmagic__enum_1_1detail_1_1underlying__type_3_01_t_00_01true_01_4.html", null ]
      ] ],
      [ "is_scoped_enum", "d5/d84/structmagic__enum_1_1is__scoped__enum.html", null ],
      [ "is_unscoped_enum", "dd/dfa/structmagic__enum_1_1is__unscoped__enum.html", null ],
      [ "underlying_type", "d6/d6e/structmagic__enum_1_1underlying__type.html", null ]
    ] ],
    [ "MyLibrary", "d5/d34/namespace_my_library.html", [
      [ "Example", "d4/d17/class_my_library_1_1_example.html", "d4/d17/class_my_library_1_1_example" ],
      [ "SubclassExample", "d7/d0a/class_my_library_1_1_subclass_example.html", "d7/d0a/class_my_library_1_1_subclass_example" ]
    ] ],
    [ "AssignAST", "d7/db1/class_assign_a_s_t.html", "d7/db1/class_assign_a_s_t" ],
    [ "AST", "da/dc8/class_a_s_t.html", "da/dc8/class_a_s_t" ],
    [ "BinOpAST", "d2/dc9/class_bin_op_a_s_t.html", "d2/dc9/class_bin_op_a_s_t" ],
    [ "BlockAST", "d0/de0/class_block_a_s_t.html", "d0/de0/class_block_a_s_t" ],
    [ "CallAST", "da/dd1/class_call_a_s_t.html", "da/dd1/class_call_a_s_t" ],
    [ "CodeGenVisitor", "da/d38/class_code_gen_visitor.html", "da/d38/class_code_gen_visitor" ],
    [ "CompoundAST", "da/dbb/class_compound_a_s_t.html", "da/dbb/class_compound_a_s_t" ],
    [ "ConstAST", "d6/d94/class_const_a_s_t.html", "d6/d94/class_const_a_s_t" ],
    [ "GraphvizVisitor", "d0/dc3/class_graphviz_visitor.html", "d0/dc3/class_graphviz_visitor" ],
    [ "HighlightAccurateVisitor", "d2/dd3/class_highlight_accurate_visitor.html", "d2/dd3/class_highlight_accurate_visitor" ],
    [ "ifAST", "d4/de5/classif_a_s_t.html", "d4/de5/classif_a_s_t" ],
    [ "IToken", "d0/d11/class_i_token.html", "d0/d11/class_i_token" ],
    [ "IVisitor", "df/db7/class_i_visitor.html", "df/db7/class_i_visitor" ],
    [ "Lexer", "da/d5a/class_lexer.html", "da/d5a/class_lexer" ],
    [ "List", "d1/d34/class_list.html", "d1/d34/class_list" ],
    [ "Node", "dc/d8f/class_node.html", "dc/d8f/class_node" ],
    [ "NodeIterator", "d3/dde/class_node_iterator.html", "d3/dde/class_node_iterator" ],
    [ "NoOpAST", "db/db7/class_no_op_a_s_t.html", "db/db7/class_no_op_a_s_t" ],
    [ "NumberAST", "d8/d90/class_number_a_s_t.html", "d8/d90/class_number_a_s_t" ],
    [ "ProgramAST", "de/db2/class_program_a_s_t.html", "de/db2/class_program_a_s_t" ],
    [ "Queue", "d4/da4/class_queue.html", "d4/da4/class_queue" ],
    [ "Stack", "d0/d14/class_stack.html", "d0/d14/class_stack" ],
    [ "StringAST", "d0/d21/class_string_a_s_t.html", "d0/d21/class_string_a_s_t" ],
    [ "SyntaxAnalyzer", "d0/dfe/class_syntax_analyzer.html", "d0/dfe/class_syntax_analyzer" ],
    [ "Token", "db/dc1/class_token.html", "db/dc1/class_token" ],
    [ "TokenTemplate", "dc/dca/class_token_template.html", "dc/dca/class_token_template" ],
    [ "TypeSpecAST", "d2/db9/class_type_spec_a_s_t.html", "d2/db9/class_type_spec_a_s_t" ],
    [ "TypeViewVisitor", "d1/d49/class_type_view_visitor.html", "d1/d49/class_type_view_visitor" ],
    [ "UnOpAST", "dc/de8/class_un_op_a_s_t.html", "dc/de8/class_un_op_a_s_t" ],
    [ "VarAST", "dc/dff/class_var_a_s_t.html", "dc/dff/class_var_a_s_t" ],
    [ "VarDeclAST", "d6/d7c/class_var_decl_a_s_t.html", "d6/d7c/class_var_decl_a_s_t" ],
    [ "VisitorValue", "d6/df2/class_visitor_value.html", "d6/df2/class_visitor_value" ],
    [ "whileAST", "d4/dae/classwhile_a_s_t.html", "d4/dae/classwhile_a_s_t" ]
];