name: C/C++ Build & Test & Memory Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
      
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: configure
        run: ./configure.sh
        
      - name: build
        run: ./allBuild.sh
        
      - name: simpleTest
        run: ./testAll.sh
        
      - name: memoryTest
        run: ./valgrindTest.sh
