name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure.sh
      
    - name: switch to gcc-10 on linux
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
        sudo update-alternatives --set gcc /usr/bin/gcc-11
      
    - name: make
      run: ./allBuild.sh
    
    - name: simpleTest
      run: ./testAll.sh

    - name: memoryTest
      run: ./valgrindTest.sh
  
